### ISSUE TITLE
Unexpected token during webpack compile after update to 4

### ISSUE THREAD

**Issue by UX-Unicorn** [garycourt/uri-js#30]
After updating to 4 I am getting the following error when I try to compile using webpack 3.11

Unexpected token: name (e) [./node_modules/fni-base/node_modules/uri-js/dist/esnext/uri.js:42,0]

**Comment by garycourt** [comment]
No idea, but I'm assuming the issue is related to what was brought up in #28 . Essentially, Webpack is using the `module` property in package.json when it doesn't support ES6+. I've been meaning to get around to creating a ES5+Modules dist for this scenario, but haven't had time to get around to it.

In the mean time, you can work around this by ensuring your compiler (usually Babel) and minifier handle ES6+ features

**Comment by UX-Unicorn** [comment]
We are using Babel. We have these presets.
'babel-preset-react',
        'stage-0',
        'es2015',
        ['babel-preset-env', {
          modules: false,
          targets: {
            ie9: true,
          },
          uglify: true,
        }],
      ]
    },
  }]

Is there another one we should be using?

**Comment by garycourt** [comment]
Sorry, questions like that are outside the scope of URI.js. I can't help you with that.

**Comment by garycourt** [comment]
The latest version of URI.js (`uri-js@^4.2.2`) should fix this issue.
